server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
